name: cargo-semver-checks
permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    paths: ['**/Cargo.toml']
  workflow_dispatch:

jobs:
  semver-checks:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev pkg-config
      - uses: obi1kenobi/cargo-semver-checks-action@v2
